### ISSUE TITLE
Excelaufstellung der Änderungen bei Versionsübergängen

### ISSUE THREAD

**Issue by timorosenblatt** [gematik/api-erp#10]
Könnt ihr bitte noch unter https://github.com/gematik/api-erp/blob/master/docs/erp_fhirversion_changes.adoc 
die in der Sprechstunde angesprochene Exceldatei, die die Änderungen der Profile zusammenfasst, mit bereitstellen?

**Comment by SvenSommer** [comment]
Hallo Timo,
die in der Sprechstunde gezeigten Exceltabellen waren ein "internes" technisches Hilfsmittel die Zuordnung der Profile grafisch zu lösen und stehen (leider) nicht mehr zur Verfügung.
Die Information zur Zuordnung der Profilen findet sich jetzt strukturiert in den [Transitionfiles](https://github.com/gematik/api-erp/blob/master/docs/erp_fhirversion_changes.adoc#download-transitionfiles).

Die _Transitionfiles_ der einzelnen Pakete sind strukturiert einlesbar und geben Auskunft über:

- Abhängigkeiten die für den Vergleich der Profile notwendig sind
- Neue Profile seit dem Versionsübergang
- Ausgeschiedene Profile mit dem Versionsübergang
- Profiländerungen mit den Versionsübergang

Weitere Vorteile einer _Transitionfiles_ sind, das diese sowohl vom Inhalt als auch vom Format her versioniert sind.

Hilft euch das?

**Comment by timorosenblatt** [comment]
Leider reicht das nicht so wirklich.
Als erstes Beispiel wäre z.B. die Änderung des NamingSystem der PrescriptionID von https://gematik.de/fhir/NamingSystem/PrescriptionID zu https://gematik.de/fhir/erp/NamingSystem/GEM_ERP_NS_PrescriptionId nicht enthalten.

Auch die Änderung von https://fhir.kbv.de/StructureDefinition/KBV_EX_ERP_Accident zu https://fhir.kbv.de/StructureDefinition/KBV_EX_FOR_Accident oder die Änderung der Schreibweise der darin enthaltenen Extensions (unfallkennzeichen->**U**nfallkennzeichen, unfallbetrieb->**U**nfallbetrieb, ...) sind nicht enthalten.

Soweit ich das in der Sprechstunde gesehen hatte wären solche Übergänge in dem Excelfile enthalten gewesen.

**Comment by SvenSommer** [comment]
**Zusammenhang Exceltabelle und Transitionfiles**
Leider ist die Änderung eines Namingsystems auch nicht in der Exceltabelle behandelt worden. Die gezeigte Exceltabelle war Grundlage für die Erstellung der Transititonfiles und hat keinen Mehrwert gegenüber dieser. Ganz sicher! 

**Vergleich von NamingSystems**
Nun aber zum eigentlichen Kern der Sache. Transitionfiles eignen sich für den Vergleich auf Ebene der FHIR _Profile_, und dienen u.a. als Grundlage für den automatisierten Aufruf der Vergelichsfunktion des Hapi Validators . 

Die Änderung des genannten _NamingSystems_ ist eine inhaltliche Änderung der Profile die durch die zur Verfügung gestellten Vergleichsartefakte(html-Seiten) sichtbar gemacht wird: z.B. [hier](https://htmlpreview.github.io/?https://raw.githubusercontent.com/gematik/api-erp/master/docs/resources/compare_results/de.abda.eRezeptAbgabedatenBasis/DAV-PR-Base-AbgabedatenBundle/sd-DAV-PR-Base-AbgabedatenBundle-DAV-PR-Base-AbgabedatenBundle.html).
Noch einmal anders formuliert: _NamingSystems_ sind FHIR technisch nur ein String in einem Profil und kein eigenes Profil.

**aktuelle Unvollständigkeit der Transitionfiles**
Die Änderung von https://fhir.kbv.de/StructureDefinition/KBV_EX_ERP_Accident zu https://fhir.kbv.de/StructureDefinition/KBV_EX_FOR_Accident war bisher noch nicht in den Transitionfiles hinterlegt (tauchte bisher noch unter „unknown“ auf), da die Abwanderung in das kbv.ita.for bisher nicht identifiziert hatten. Wir werden in der kommenden Woche diese letzten dunklen Flecken ausleuchten und dann sowohl die aktualisierten Transitionfiles als auch die neuen Vergleichsartefakte zur Verfügung stellen.

**Comment by SvenSommer** [comment]
Falls es noch weitere Nachfragen oder Verbesserungsvorschläge gibt, bitte das Issue wieder öffnen.
