### ISSUE TITLE
Preflight request auf https://idp-ref.app.ti-dienste.de/.well-known/openid-configuration

### ISSUE THREAD

**Issue by christophgapp** [gematik/api-erp#117]
Leider ist es nicht möglich, mit der JavaScript-API des Browsers (fetch, Axios) die Ressource https://idp-ref.app.ti-dienste.de/.well-known/openid-configuration aufzurufen. Die CORS-Einstellungen des Servers erlauben dies nicht. Ist dies beabsichtigt, bzw. haben Sie eine alternative Implementierung dafür vorgesehen?

**Comment by florianschoffke** [comment]
Diese Frage hat nicht direkt mit dem E-Rezept sondern eher mit IDP zu tun. Daher würde ich Sie bitten eine Anfrage an das Identity Management Team zu stellen: https://service.gematik.de/servicedesk/customer/portal/33
