### ISSUE TITLE
Zugriff auf Konnektor über URLs statt IPs

### ISSUE THREAD

**Issue by AntiGuideAkquinet** [gematik/api-erp#139]
In der Dokumentation über den Abruf von eRezepten und vermutlich an vielen anderen Stellen wird der Aufruf an den Konnektor mit einer Beispielhaften IP angegeben. Vlt. wäre es besser hier direkt von `konnektor.konlan` auszugehen, und die Information über die CA-Zertifikate die zur Validierung heruntergeladen werden müssen anzufügen.

Diese Infomationen könnten auch gesammelt im Thema Netzwerkkonfiguration (ti_configuration.adoc) behandelt werden. Eine Auflistung der Zertifikatsdownload als Liste wäre sicher hilfreich:
- PU: https://download.tsl.ti-dienste.de
- RU: https://download-ref.tsl.ti-dienste.de/
- TU: https://download-test.tsl.ti-dienste.de/

**Comment by Hendrejvr** [comment]
Vielen Dank für den Vorschlag. Stellen Sie uns gerne ein Pull Request mit dem konkreten Vorschlag zur Verfügung, damit wir das reviewen können.
