### ISSUE TITLE
Löschen einer Nachricht als Versicherter möglich?

### ISSUE THREAD

**Issue by wengelef** [gematik/api-erp#17]
ist nicht einer der Andwendungsfälle, eine Nachricht als Versicherter zu löschen?

https://github.com/gematik/api-erp/blob/master/docs/erp_communication.adoc#anwendungsfall-nachricht-als-apotheke-löschen

**Comment by HendrikGematik** [comment]
Hallo wengelef,

ja das ist vorgesehen. Jeder Nutzer soll von ihm gesendete Nachrichten löschen können (vgl. A_20258 in gemSpec_FD_eRp und A_21525 in gemSpec_eRp_FdV).
Aufgrund der aktuell schwachen Verbreitung von eGK inkl. PIN, ist der Nutzerkreis für die App aktuell leider immernoch sehr klein. Dieser Anwendungsfall ist obendrein nicht der Default, in der App erfolgt die Zuweisung "aus der Ferne" in einer orchestrierten Nutzung der Communications-Nachrichten. Freitext-Kommunikation unterstützt die App derzeit nicht. Daher haben wir drauf verzichtet, diesen Anwendungsfall hier aufzuschreiben. Technisch unterstützt das Backend dieses. Wir beobachten aber erstmal den Rollout und wie die Nutzer mit der App interagieren. 

Viele Grüße
Hendrik
