### ISSUE TITLE
Einbindung von Dritten

### ISSUE THREAD

**Issue by wonderix** [gematik/api-erp#2]
In dieser Spezifikation wird nicht dargestellt wie Dritte in den Prozess eingebunden werden können. Die folgenden beispielhaften Fälle sollten von der Spezifikation abgedeckt werden:
- Wie kann ein Altenheim überprüfen, ob ein ausgestelltes Rezept korrekt ist?
- Wie kann ein pflegender Angehöriger ein Rezept einlösen?
- Wie kann ein Altenheim Rezepte für einen Bewohner anfordern?

**Comment by HendrikGematik** [comment]
Hallo @wonderix wir geben in dieser API-Beschreibung eine Implementierungshilfe für die Benutzung der Schnittstellen. Organisatorische Prozesse und UseCases der Clients in Arztpraxis und Apotheke sind zum einen im Implementierungsleitfaden beschrieben. Zum anderen arbeitet unser App-Team mit Testnutzern an der stetigen Verbesserung der UX und auch an der Weiterentwicklung der UseCases.

Das Thema Heimversorgung ist ein weites Feld mit vielen weiteren Beteiligten und Regelungen zur Arzneimittelversorgung. Melden sie sich gern direkt bei uns unter https://fachportal.gematik.de/kontakt evtl. finden sie auch weitere Informationen auf https://fachportal.gematik.de/anwendungen/elektronisches-rezept
