### ISSUE TITLE
erp_consent.adoc -> Hinweis, für Nutzbarkeit ausschließlich aus der Gematik-App ergänzen 

### ISSUE THREAD

**Issue by bneidhold** [gematik/api-erp#26]
erp_consent.adoc
hier und ggf. in anderen parallelen Dokudateien wäre es sinnvoll gleich am Anfang klar zu machen, welches System (PVS, AVS oder eben NUR Gematik-App) diese API nutzen darf.

**Comment by SvenSommer** [comment]
Hallo Benjamin,
vielen Dank für deine Idee. Wir werden uns überlegen, wie wir die Zielgruppe der Dokumente/Features klarer kommunizieren können.

**Comment by pke** [comment]
Ist es denn korrekt, dass ich mir als Versicherter eine eigene App schreiben könnte, welche mit den eGK Kartendaten via IDP generierter AccessTokens meine Rezepte verwalten kann? Oder bedarf so eine App der Zertifizierung durch die gematik?

**Comment by pke** [comment]
Danke für die Antwort @florianschoffke 
Das hatte ich mir schon gedacht, dass es einer Form der Registrierung als Anbieter bedarf. Das Fachportal kenne ich natürlich schon, finde dort jedoch nur etwas zu bereits erfolgten Zulassungen nichts wo man sich als E-Rezept Client App registrieren kann. 
Hat der Gesetzgeber keine Möglichkeit vorgesehen, dass der Patient auch ohne die Gematik App, sondern mit einer von ihm selbst entwickelten App, auf seine Rezeptdaten zugreifen kann?

**Comment by florianschoffke** [comment]
Das Digitalgesetz wird voraussichtlich im Februar wirksam und regelt Apps der Krankenkassen, Apps einzelner Apotheken und Apps von Plattformen. Apps die via CardLink sich an eine Apotheke anbinden sind gesetzlich nicht weiter geregelt. Direkte Anbindung von Privatpersonen mit einer App an den IDP oder Fachdienst sind nicht vorgesehen.

**Comment by florianschoffke** [comment]
Auch wenn es etwas gedauert hat haben wir mit #161 eine Verbesserung eingebracht, die kenntlich macht, wen die API Beschreibung und deren UseCases betrifft.
