### ISSUE TITLE
/ChargeItem/<taskId> oder /ChargeItem?task=<taskId>

### ISSUE THREAD

**Issue by joergreichert** [gematik/api-erp#65]
Bei https://github.com/gematik/api-erp/blob/master/docs/erp_chargeItem.adoc#anwendungsfall-abrechnungsinformation-zum-ändern-abrufen bekomme ich für `https://prescriptionserver.telematik/ChargeItem/200.000.000.022.127.38?ac=777bea0e13cc9c42ceec14aec3ddee2263325dc2c6c699db115f58fe423607ea`

```
<?xml version="1.0" encoding="utf-8"?>
<OperationOutcome xmlns="http://hl7.org/fhir"><meta><profile value="http://hl7.org/fhir/StructureDefinition/OperationOutcome"/></meta><issue><severity value="error"/><code value="not-supported"/><details><text value="no matching handler found."/></details></issue></OperationOutcome>
```

Ich vermute, dass analog zu https://github.com/gematik/api-erp/blob/master/docs/erp_chargeItem.adoc#anwendungsfall-pkv-abrechnungsinformationen-durch-den-abgebenden-leistungserbringer-bereitstellen der Aufruf `https://prescriptionserver.telematik/ChargeItem?task=200.000.000.022.127.38&ac=777bea0e13cc9c42ceec14aec3ddee2263325dc2c6c699db115f58fe423607ea` lauten müsste. 

Bekomme dann allerdings

```
<?xml version="1.0" encoding="utf-8"?>
<OperationOutcome xmlns="http://hl7.org/fhir"><meta><profile value="http://hl7.org/fhir/StructureDefinition/OperationOutcome"/></meta><issue><severity value="error"/><code value="forbidden"/><details><text value="No or invalid secret provided for referenced Task"/></details></issue></OperationOutcome>
```
Bin mir also nicht sicher, ob es wirklich daran liegt (invalid secret, obwohl ja hier der access code angegeben werden soll, oder ist es nur ein Wording-Problem in der Fehlermeldung?).

**Comment by florianschoffke** [comment]
Hallo @joergreichert,
Bei den in der API aufgeführten Beispielen sind Kürzungen enthalten. Z.B. `<data value="MII1IgYJKo..." />`.
Daher sind diese Beispiele nicht valide und können entsprechend zu Fehlern führen.

Im E-Rezept Examples Repo finden Sie weitere Beispiele. Z.B. hier: 
https://github.com/gematik/eRezept-Examples/tree/main/Test-Scenarios/2023-07-01/Versicherter/l%C3%B6schen_der_pkv_abrechnungsinformationen_durch_den_versicherten

Möglicherweise funktioniert das mit dem Beispiel besser.

**Comment by joergreichert** [comment]
Hallo @florianschoffke,

Danke für den Link auf die Beispiele, wobei man bei diesen den Aufbau vom REST-Request nicht sieht. Ich hatte jetzt schon mit einem selbst erstellten PKV-Rezept in der RU getestet und auch den Request entsprechend programmatisch bei uns aufgebaut. 

Der Request für https://github.com/gematik/api-erp/blob/master/docs/erp_chargeItem.adoc#anwendungsfall-pkv-abrechnungsinformationen-durch-den-abgebenden-leistungserbringer-bereitstellen ist zu mindestens so weit durchgekommen, dass die Signatur-Prüfung fehlgeschlagen ist. 
```
<?xml version="1.0" encoding="utf-8"?>
<OperationOutcome xmlns="http://hl7.org/fhir">
  <meta>
    <profile value="http://hl7.org/fhir/StructureDefinition/OperationOutcome"/>
  </meta>
  <issue>
    <severity value="error"/>
    <code value="invalid"/>
    <details>
      <text value="CAdES-BES signature verification has failed: d2i_CMS_bio failed. error:0D0680A8:asn1 encoding routines:asn1_check_tlen:wrong tag; error:0D07803A:asn1 encoding routines:asn1_item_embed_d2i:nested asn1 error"/>
    </details>
  </issue>
</OperationOutcome>
``` 

Wahrscheinlich also ist der Abgabendatensatz falsch von mir signiert (obwohl eigentlich mit SMC-B-Karte signiert) und bekomme daher nicht den Access-Code, der zum Ändern der Abrechnung berechtigt, zurück. 

Und wenn ich beim Abrufen stattdessen den Access-Code, der im $accept enthalten ist, nutze, gibt es logischerweise den Fehler, dass der access code fehlt/falsch ist.

D.h. der Aufruf `https://prescriptionserver.telematik/ChargeItem/<taskId>?ac=<accessCode für Änderung>` ist entweder trotzdem in https://github.com/gematik/api-erp/blob/master/docs/erp_chargeItem.adoc#anwendungsfall-abrechnungsinformation-zum-%C3%A4ndern-abrufen falsch und müsste `https://prescriptionserver.telematik/ChargeItem?task=<taskId>?ac=<accessCode für Änderung>` lauten (bei https://github.com/gematik/api-erp/blob/master/docs/erp_chargeItem.adoc#anwendungsfall-pkv-abgabedatensatz-ändern dann genauso) *oder* `.../ChargeItem/<taskId>...` ist doch richtig, sollte dann aber eher einen 404 zurückgeben, wenn das ChargeItem noch nicht existiert (statt "no matching handler found.")?

**Comment by florianschoffke** [comment]
Hallo @joergreichert,
hier ist ein Beispielaufruf von unserem Test-Team der in der RU funktioniert. Der Access Code muss vom Versicherten bereitgestellt werden.

PUT /ChargeItem/200.000.000.576.697.72?ac=1d213cb55818c1067a7f336f7afa89be9cb3244b6b35295bf283d00b9c42a8a2

`<ChargeItem xmlns="http://hl7.org/fhir">
   <id value="200.000.000.576.697.72"/>
   <meta>
      <profile value="https://gematik.de/fhir/erpchrg/StructureDefinition/GEM_ERPCHRG_PR_ChargeItem|1.0"/>
   </meta>
   <contained>
      <Binary xmlns="http://hl7.org/fhir">
         <id value="32e05db0-ba40-4967-9d7f-4b0bc19bd5e9"/>
         <contentType value="application/pkcs7-mime"/>
         <data value="MIIe4QYJKoZIhvcNAQcCoIIe0jCCHs4CAQExDTALBglghkgBZQMEAgEwghXaBgkqhkiG9w0BBwGgghXLBIIVxzxCdW5kbGUgeG1sbnM9Imh0dHA6Ly9obDcub3JnL2ZoaXIiPjxpZCB2YWx1ZT0iMzJlMDVkYjAtYmE0MC00OTY3LTlkN2YtNGIwYmMxOWJkNWU5Ii8+PG1ldGE+PGxhc3RVcGRhdGVkIHZhbHVlPSIyMDIzLTA2LTA1VDAxOjA1OjQyLjE2OSswMjowMCIvPjxwcm9maWxlIHZhbHVlPSJodHRwOi8vZmhpci5hYmRhLmRlL2VSZXplcHRBYmdhYmVkYXRlbi9TdHJ1Y3R1cmVEZWZpbml0aW9uL0RBVi1QS1YtUFItRVJQLUFiZ2FiZWRhdGVuQnVuZGxlfDEuMiIvPjwvbWV0YT48aWRlbnRpZmllcj48c3lzdGVtIHZhbHVlPSJodHRwczovL2dlbWF0aWsuZGUvZmhpci9lcnAvTmFtaW5nU3lzdGVtL0dFTV9FUlBfTlNfUHJlc2NyaXB0aW9uSWQiLz48dmFsdWUgdmFsdWU9IjIwMC4wMDAuMDAwLjU3Ni42OTcuNzIiLz48L2lkZW50aWZpZXI+PHR5cGUgdmFsdWU9ImRvY3VtZW50Ii8+PHRpbWVzdGFtcCB2YWx1ZT0iMjAyMy0wNi0wNVQwMTowNTo0Mi4xNjkrMDI6MDAiLz48ZW50cnk+PGZ1bGxVcmwgdmFsdWU9InVybjp1dWlkOjg1OWI5ZTMxLWMzMjUtNDE5OS1iMmUzLTZjZmU4NDQ0ZTJiOCIvPjxyZXNvdXJjZT48Q29tcG9zaXRpb24geG1sbnM9Imh0dHA6Ly9obDcub3JnL2ZoaXIiPjxpZCB2YWx1ZT0iODU5YjllMzEtYzMyNS00MTk5LWIyZTMtNmNmZTg0NDRlMmI4Ii8+PG1ldGE+PHByb2ZpbGUgdmFsdWU9Imh0dHA6Ly9maGlyLmFiZGEuZGUvZVJlemVwdEFiZ2FiZWRhdGVuL1N0cnVjdHVyZURlZmluaXRpb24vREFWLVBLVi1QUi1FUlAtQWJnYWJlZGF0ZW5Db21wb3NpdGlvbnwxLjIiLz48L21ldGE+PHN0YXR1cyB2YWx1ZT0iZmluYWwiLz48dHlwZT48Y29kaW5nPjxzeXN0ZW0gdmFsdWU9Imh0dHA6Ly9maGlyLmFiZGEuZGUvZVJlemVwdEFiZ2FiZWRhdGVuL0NvZGVTeXN0ZW0vREFWLUNTLUVSUC1Db21wb3NpdGlvblR5cGVzIi8+PGNvZGUgdmFsdWU9IkVSZXplcHRBYmdhYmVkYXRlbiIvPjwvY29kaW5nPjwvdHlwZT48ZGF0ZSB2YWx1ZT0iMjAyMy0wNi0wNVQwMTowNTo0MiswMjowMCIvPjxhdXRob3I+PHJlZmVyZW5jZSB2YWx1ZT0idXJuOnV1aWQ6NWQ2ZjJjNDYtZWRhNC00Y2I3LWJkYjMtYTczZjY4YWFhN2JmIi8+PC9hdXRob3I+PHRpdGxlIHZhbHVlPSJFUmV6ZXB0QWJnYWJlZGF0ZW4iLz48c2VjdGlvbj48dGl0bGUgdmFsdWU9IkFwb3RoZWtlIi8+PGVudHJ5PjxyZWZlcmVuY2UgdmFsdWU9InVybjp1dWlkOjVkNmYyYzQ2LWVkYTQtNGNiNy1iZGIzLWE3M2Y2OGFhYTdiZiIvPjwvZW50cnk+PC9zZWN0aW9uPjxzZWN0aW9uPjx0aXRsZSB2YWx1ZT0iQWJnYWJlaW5mb3JtYXRpb25lbiIvPjxlbnRyeT48cmVmZXJlbmNlIHZhbHVlPSJ1cm46dXVpZDpmMTJjYmEwMC02ZDZiLTQwYzctYTRiNC0wZGEwMjg1OTEwYmQiLz48L2VudHJ5Pjwvc2VjdGlvbj48L0NvbXBvc2l0aW9uPjwvcmVzb3VyY2U+PC9lbnRyeT48ZW50cnk+PGZ1bGxVcmwgdmFsdWU9InVybjp1dWlkOjVkNmYyYzQ2LWVkYTQtNGNiNy1iZGIzLWE3M2Y2OGFhYTdiZiIvPjxyZXNvdXJjZT48T3JnYW5pemF0aW9uIHhtbG5zPSJodHRwOi8vaGw3Lm9yZy9maGlyIj48aWQgdmFsdWU9IjVkNmYyYzQ2LWVkYTQtNGNiNy1iZGIzLWE3M2Y2OGFhYTdiZiIvPjxtZXRhPjxwcm9maWxlIHZhbHVlPSJodHRwOi8vZmhpci5hYmRhLmRlL2VSZXplcHRBYmdhYmVkYXRlbi9TdHJ1Y3R1cmVEZWZpbml0aW9uL0RBVi1QS1YtUFItRVJQLUFwb3RoZWtlfDEuMiIvPjwvbWV0YT48aWRlbnRpZmllcj48c3lzdGVtIHZhbHVlPSJodHRwOi8vZmhpci5kZS9zaWQvYXJnZS1pay9pa25yIi8+PHZhbHVlIHZhbHVlPSI2MzU4NDAyODYiLz48L2lkZW50aWZpZXI+PG5hbWUgdmFsdWU9IkFwb3RoZWtlIEpvZSBLZXJyIi8+PGFkZHJlc3M+PHR5cGUgdmFsdWU9InBoeXNpY2FsIi8+PGxpbmUgdmFsdWU9IkltIFJvc2VuZ2FydGVuIDc1YSI+PGV4dGVuc2lvbiB1cmw9Imh0dHA6Ly9obDcub3JnL2ZoaXIvU3RydWN0dXJlRGVmaW5pdGlvbi9pc28yMTA5MC1BRFhQLWhvdXNlTnVtYmVyIj48dmFsdWVTdHJpbmcgdmFsdWU9Ijc1YSIvPjwvZXh0ZW5zaW9uPjxleHRlbnNpb24gdXJsPSJodHRwOi8vaGw3Lm9yZy9maGlyL1N0cnVjdHVyZURlZmluaXRpb24vaXNvMjEwOTAtQURYUC1zdHJlZXROYW1lIj48dmFsdWVTdHJpbmcgdmFsdWU9IkltIFJvc2VuZ2FydGVuIi8+PC9leHRlbnNpb24+PC9saW5lPjxjaXR5IHZhbHVlPSJMZW5pYmVyZyIvPjxwb3N0YWxDb2RlIHZhbHVlPSI5NDc5OCIvPjxjb3VudHJ5IHZhbHVlPSJEIi8+PC9hZGRyZXNzPjwvT3JnYW5pemF0aW9uPjwvcmVzb3VyY2U+PC9lbnRyeT48ZW50cnk+PGZ1bGxVcmwgdmFsdWU9InVybjp1dWlkOmQ2N2UyMzRkLWM1OTgtNDVmZi1hZDFiLTAxZTM0MjFhZDQ4OCIvPjxyZXNvdXJjZT48SW52b2ljZSB4bWxucz0iaHR0cDovL2hsNy5vcmcvZmhpciI+PGlkIHZhbHVlPSJkNjdlMjM0ZC1jNTk4LTQ1ZmYtYWQxYi0wMWUzNDIxYWQ0ODgiLz48bWV0YT48cHJvZmlsZSB2YWx1ZT0iaHR0cDovL2ZoaXIuYWJkYS5kZS9lUmV6ZXB0QWJnYWJlZGF0ZW4vU3RydWN0dXJlRGVmaW5pdGlvbi9EQVYtUEtWLVBSLUVSUC1BYnJlY2hudW5nc3plaWxlbnwxLjIiLz48L21ldGE+PHN0YXR1cyB2YWx1ZT0iaXNzdWVkIi8+PHR5cGU+PGNvZGluZz48c3lzdGVtIHZhbHVlPSJodHRwOi8vZmhpci5hYmRhLmRlL2VSZXplcHRBYmdhYmVkYXRlbi9Db2RlU3lzdGVtL0RBVi1DUy1FUlAtSW52b2ljZVR5cCIvPjxjb2RlIHZhbHVlPSJBYnJlY2hudW5nc3plaWxlbiIvPjwvY29kaW5nPjwvdHlwZT48bGluZUl0ZW0+PHNlcXVlbmNlIHZhbHVlPSIxIi8+PGNoYXJnZUl0ZW1Db2RlYWJsZUNvbmNlcHQ+PGNvZGluZz48c3lzdGVtIHZhbHVlPSJodHRwOi8vZmhpci5kZS9Db2RlU3lzdGVtL2lmYS9wem4iLz48Y29kZSB2YWx1ZT0iOTY3NTEwMTYiLz48L2NvZGluZz48dGV4dCB2YWx1ZT0iQnVzdm9taWxwYW0iLz48L2NoYXJnZUl0ZW1Db2RlYWJsZUNvbmNlcHQ+PHByaWNlQ29tcG9uZW50PjxleHRlbnNpb24gdXJsPSJodHRwOi8vZmhpci5hYmRhLmRlL2VSZXplcHRBYmdhYmVkYXRlbi9TdHJ1Y3R1cmVEZWZpbml0aW9uL0RBVi1FWC1FUlAtS29zdGVuVmVyc2ljaGVydGVyIj48ZXh0ZW5zaW9uIHVybD0iS2F0ZWdvcmllIj48dmFsdWVDb2RlYWJsZUNvbmNlcHQ+PGNvZGluZz48c3lzdGVtIHZhbHVlPSJodHRwOi8vZmhpci5hYmRhLmRlL2VSZXplcHRBYmdhYmVkYXRlbi9Db2RlU3lzdGVtL0RBVi1QS1YtQ1MtRVJQLUtvc3RlblZlcnNpY2hlcnRlckthdGVnb3JpZSIvPjxjb2RlIHZhbHVlPSIwIi8+PC9jb2Rpbmc+PC92YWx1ZUNvZGVhYmxlQ29uY2VwdD48L2V4dGVuc2lvbj48ZXh0ZW5zaW9uIHVybD0iS29zdGVuYmV0cmFnIj48dmFsdWVNb25leT48dmFsdWUgdmFsdWU9Ijk1LjI1Ii8+PGN1cnJlbmN5IHZhbHVlPSJFVVIiLz48L3ZhbHVlTW9uZXk+PC9leHRlbnNpb24+PC9leHRlbnNpb24+PGV4dGVuc2lvbiB1cmw9Imh0dHA6Ly9maGlyLmFiZGEuZGUvZVJlemVwdEFiZ2FiZWRhdGVuL1N0cnVjdHVyZURlZmluaXRpb24vREFWLUVYLUVSUC1Nd1N0U2F0eiI+PHZhbHVlRGVjaW1hbCB2YWx1ZT0iMjEuMjEiLz48L2V4dGVuc2lvbj48dHlwZSB2YWx1ZT0iaW5mb3JtYXRpb25hbCIvPjxmYWN0b3IgdmFsdWU9IjEiLz48YW1vdW50Pjx2YWx1ZSB2YWx1ZT0iMTAwLjM5Ii8+PGN1cnJlbmN5IHZhbHVlPSJFVVIiLz48L2Ftb3VudD48L3ByaWNlQ29tcG9uZW50PjwvbGluZUl0ZW0+PHRvdGFsR3Jvc3M+PGV4dGVuc2lvbiB1cmw9Imh0dHA6Ly9maGlyLmFiZGEuZGUvZVJlemVwdEFiZ2FiZWRhdGVuL1N0cnVjdHVyZURlZmluaXRpb24vREFWLUVYLUVSUC1HZXNhbXR6dXphaGx1bmciPjx2YWx1ZU1vbmV5Pjx2YWx1ZSB2YWx1ZT0iOTUuMjUiLz48Y3VycmVuY3kgdmFsdWU9IkVVUiIvPjwvdmFsdWVNb25leT48L2V4dGVuc2lvbj48dmFsdWUgdmFsdWU9IjEwMC4zOSIvPjxjdXJyZW5jeSB2YWx1ZT0iRVVSIi8+PC90b3RhbEdyb3NzPjwvSW52b2ljZT48L3Jlc291cmNlPjwvZW50cnk+PGVudHJ5PjxmdWxsVXJsIHZhbHVlPSJ1cm46dXVpZDpmMTJjYmEwMC02ZDZiLTQwYzctYTRiNC0wZGEwMjg1OTEwYmQiLz48cmVzb3VyY2U+PE1lZGljYXRpb25EaXNwZW5zZSB4bWxucz0iaHR0cDovL2hsNy5vcmcvZmhpciI+PGlkIHZhbHVlPSJmMTJjYmEwMC02ZDZiLTQwYzctYTRiNC0wZGEwMjg1OTEwYmQiLz48bWV0YT48cHJvZmlsZSB2YWx1ZT0iaHR0cDovL2ZoaXIuYWJkYS5kZS9lUmV6ZXB0QWJnYWJlZGF0ZW4vU3RydWN0dXJlRGVmaW5pdGlvbi9EQVYtUEtWLVBSLUVSUC1BYmdhYmVpbmZvcm1hdGlvbmVufDEuMiIvPjwvbWV0YT48ZXh0ZW5zaW9uIHVybD0iaHR0cDovL2ZoaXIuYWJkYS5kZS9lUmV6ZXB0QWJnYWJlZGF0ZW4vU3RydWN0dXJlRGVmaW5pdGlvbi9EQVYtUEtWLUVYLUVSUC1BYnJlY2hudW5nc1R5cCI+PHZhbHVlQ29kZWFibGVDb25jZXB0Pjxjb2Rpbmc+PHN5c3RlbSB2YWx1ZT0iaHR0cDovL2ZoaXIuYWJkYS5kZS9lUmV6ZXB0QWJnYWJlZGF0ZW4vQ29kZVN5c3RlbS9EQVYtUEtWLUNTLUVSUC1BYnJlY2hudW5nc1R5cCIvPjxjb2RlIHZhbHVlPSIxIi8+PC9jb2Rpbmc+PC92YWx1ZUNvZGVhYmxlQ29uY2VwdD48L2V4dGVuc2lvbj48ZXh0ZW5zaW9uIHVybD0iaHR0cDovL2ZoaXIuYWJkYS5kZS9lUmV6ZXB0QWJnYWJlZGF0ZW4vU3RydWN0dXJlRGVmaW5pdGlvbi9EQVYtRVgtRVJQLUFicmVjaG51bmdzemVpbGVuIj48dmFsdWVSZWZlcmVuY2U+PHJlZmVyZW5jZSB2YWx1ZT0idXJuOnV1aWQ6ZDY3ZTIzNGQtYzU5OC00NWZmLWFkMWItMDFlMzQyMWFkNDg4Ii8+PC92YWx1ZVJlZmVyZW5jZT48L2V4dGVuc2lvbj48c3RhdHVzIHZhbHVlPSJjb21wbGV0ZWQiLz48bWVkaWNhdGlvbkNvZGVhYmxlQ29uY2VwdD48Y29kaW5nPjxzeXN0ZW0gdmFsdWU9Imh0dHA6Ly90ZXJtaW5vbG9neS5obDcub3JnL0NvZGVTeXN0ZW0vZGF0YS1hYnNlbnQtcmVhc29uIi8+PGNvZGUgdmFsdWU9Im5vdC1hcHBsaWNhYmxlIi8+PC9jb2Rpbmc+PC9tZWRpY2F0aW9uQ29kZWFibGVDb25jZXB0PjxwZXJmb3JtZXI+PGFjdG9yPjxyZWZlcmVuY2UgdmFsdWU9InVybjp1dWlkOjVkNmYyYzQ2LWVkYTQtNGNiNy1iZGIzLWE3M2Y2OGFhYTdiZiIvPjwvYWN0b3I+PC9wZXJmb3JtZXI+PGF1dGhvcml6aW5nUHJlc2NyaXB0aW9uPjxpZGVudGlmaWVyPjxzeXN0ZW0gdmFsdWU9Imh0dHBzOi8vZ2VtYXRpay5kZS9maGlyL2VycC9OYW1pbmdTeXN0ZW0vR0VNX0VSUF9OU19QcmVzY3JpcHRpb25JZCIvPjx2YWx1ZSB2YWx1ZT0iMjAwLjAwMC4wMDAuNTc2LjY5Ny43MiIvPjwvaWRlbnRpZmllcj48L2F1dGhvcml6aW5nUHJlc2NyaXB0aW9uPjx0eXBlPjxjb2Rpbmc+PHN5c3RlbSB2YWx1ZT0iaHR0cDovL2ZoaXIuYWJkYS5kZS9lUmV6ZXB0QWJnYWJlZGF0ZW4vQ29kZVN5c3RlbS9EQVYtQ1MtRVJQLU1lZGljYXRpb25EaXNwZW5zZVR5cCIvPjxjb2RlIHZhbHVlPSJBYmdhYmVpbmZvcm1hdGlvbmVuIi8+PC9jb2Rpbmc+PC90eXBlPjx3aGVuSGFuZGVkT3ZlciB2YWx1ZT0iMjAyMy0wNi0wNSIvPjwvTWVkaWNhdGlvbkRpc3BlbnNlPjwvcmVzb3VyY2U+PC9lbnRyeT48L0J1bmRsZT6gggVNMIIFSTCCBDGgAwIBAgIHA6EQzzG+qjANBgkqhkiG9w0BAQsFADCBmjELMAkGA1UEBhMCREUxHzAdBgNVBAoMFmdlbWF0aWsgR21iSCBOT1QtVkFMSUQxSDBGBgNVBAsMP0luc3RpdHV0aW9uIGRlcyBHZXN1bmRoZWl0c3dlc2Vucy1DQSBkZXIgVGVsZW1hdGlraW5mcmFzdHJ1a3R1cjEgMB4GA1UEAwwXR0VNLlNNQ0ItQ0EyNCBURVNULU9OTFkwHhcNMjAwMTI0MDAwMDAwWhcNMjQxMjExMjM1OTU5WjCB5TELMAkGA1UEBhMCREUxEDAOBgNVBAcMB0hhbWJ1cmcxDjAMBgNVBBEMBTIyNDUzMRgwFgYDVQQJDA9IZXNlbHN0w7xja2VuIDkxKjAoBgNVBAoMITMtU01DLUItVGVzdGthcnRlLTg4MzExMDAwMDExNjg3MzEdMBsGA1UEBRMUODAyNzY4ODMxMTAwMDAxMTY4NzMxEjAQBgNVBAQMCVNjaHJhw59lcjESMBAGA1UEKgwJU2llZ2ZyaWVkMScwJQYDVQQDDB5BcG90aGVrZSBhbSBGbHVnaGFmZW5URVNULU9OTFkwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDXPpn1+Rj9of5DlEZmGRSn/zfyEuuwcKuZkXFb1CRfnY1aFSUTK3l2mf59S9JmBulNzR48VZJ0VFfOpxNX7HiYt5B9/FIna8OGMAy7ZRjRIVUwoXYKaw4Uw5leHRP4Y0FcQlzc6TidhjQdrSVGKvov9Qvag6WINBVeHj/jS7Jhy2vZMBsIrTRqhYmEBqtymbFlY9QVRNMhhl2kFL+vjx6bZMyvqS5zD8IG9RXKCIiRjHBGoFzYJuIFX8RNMQSBKTW0Z3nr4QRbvzpwbtVmue1dT+E7clvT3r54baWo91Du+I1LzJWvlCUgtlnUml1rQ62MH2KF4qXIgT68HDKCjTiBAgMBAAGjggFFMIIBQTAdBgNVHQ4EFgQUkFwilc+EghFefpYaD9gTURgSpLowDgYDVR0PAQH/BAQDAgZAMCAGA1UdIAQZMBcwCgYIKoIUAEwEgSMwCQYHKoIUAEwETjA4BggrBgEFBQcBAQQsMCowKAYIKwYBBQUHMAGGHGh0dHA6Ly9laGNhLmdlbWF0aWsuZGUvb2NzcC8wHwYDVR0jBBgwFoAUeunhb+oUWRYF7gPp0/0hq97p2Z4wDAYDVR0TAQH/BAIwADCBhAYFKyQIAwMEezB5pCgwJjELMAkGA1UEBhMCREUxFzAVBgNVBAoMDmdlbWF0aWsgQmVybGluME0wSzBJMEcwFwwVw5ZmZmVudGxpY2hlIEFwb3RoZWtlMAkGByqCFABMBDYTITMtU01DLUItVGVzdGthcnRlLTg4MzExMDAwMDExNjg3MzANBgkqhkiG9w0BAQsFAAOCAQEAcJHa47UAMOpR+wuCw9BleBezXdbFw1/qxWEjDhzO/GLSZ9DBwa/v+SGXNU/FMMqH08JKU25jgW5evfBdNtoK5j/S8Cv/dTuqL0ztNQann2Ue1GtZtv5S1Ry5x+QkCje8HD6AwWZuLp/Pib4mQlLpOqvatHshggy71PDTq0YAAt8QKTee0NJApg1Ts7eZBdqPgl4QU0A47CKQXKUQ1bjWD7lEXZGSlXsqmm8//EV66Vkd8cnyquAjtZ858xKptikk1z6VMwp5PEosWwARHG1l0LzP2edpF5aUee6V282Dn/ZtvjlktQGHd9B3AfOXwSHUKJ8O0DUn3E+8JFZKtKZDujGCA4kwggOFAgEBMIGmMIGaMQswCQYDVQQGEwJERTEfMB0GA1UECgwWZ2VtYXRpayBHbWJIIE5PVC1WQUxJRDFIMEYGA1UECww/SW5zdGl0dXRpb24gZGVzIEdlc3VuZGhlaXRzd2VzZW5zLUNBIGRlciBUZWxlbWF0aWtpbmZyYXN0cnVrdHVyMSAwHgYDVQQDDBdHRU0uU01DQi1DQTI0IFRFU1QtT05MWQIHA6EQzzG+qjALBglghkgBZQMEAgGgggG1MBgGCSqGSIb3DQEJAzELBgkqhkiG9w0BBwEwHAYJKoZIhvcNAQkFMQ8XDTIzMDYwNDIzMDU0MlowKwYJKoZIhvcNAQk0MR4wHDALBglghkgBZQMEAgGhDQYJKoZIhvcNAQELBQAwLwYJKoZIhvcNAQkEMSIEIM6qrFNfq4jMdAOU1TZiANp+QagaZlUTEVG8SLHbwkXwMDAGCyqGSIb3DQEJEAIEMSEwHwwQQ01TRG9jdW1lbnQyc2lnbgYLKoZIhvcNAQkQAgQwgeoGCyqGSIb3DQEJEAIvMYHaMIHXMIHUMIHRBCDuhNK4ZE8CVMylx1JXHScZTYhXOPEooyMUkA/Ua8eqDjCBrDCBoKSBnTCBmjELMAkGA1UEBhMCREUxHzAdBgNVBAoMFmdlbWF0aWsgR21iSCBOT1QtVkFMSUQxSDBGBgNVBAsMP0luc3RpdHV0aW9uIGRlcyBHZXN1bmRoZWl0c3dlc2Vucy1DQSBkZXIgVGVsZW1hdGlraW5mcmFzdHJ1a3R1cjEgMB4GA1UEAwwXR0VNLlNNQ0ItQ0EyNCBURVNULU9OTFkCBwOhEM8xvqowDQYJKoZIhvcNAQELBQAEggEA1UnofjvUaTvLg/MKCFUXgZ/722Y1Znb3GLz7OJBrz7TtNU0UdOy4uicy2Kk1VUsL0WFfYt4YtMrQZxr9VzvEW0csOSx6B30ZDbxUX0W5XIetH80pdG8yLZdZKg/bkfETOXrU2PS0h8jhR5H1ljYKdLmViVJe2lM5v0o5Fg67p05BAHQT2UCoIyS5fi19JV2kaFc9dTGAJtHKthPT4tU1AhavN4RUQ4o2rn3+nJP+ZKfskbQIAlt4f9yfE2c+9dUKf8QnCbrC90kgYKOySnzX/p7EdWnIThE2Y2HiwDj684W6RVkNh9Z27O2QvNBVN8Mtvr1UYii5SfEGXFnMM6qeGg=="/>
      </Binary>
   </contained>
   <identifier>
      <system value="https://gematik.de/fhir/erp/NamingSystem/GEM_ERP_NS_AccessCode"/>
      <value value="1d213cb55818c1067a7f336f7afa89be9cb3244b6b35295bf283d00b9c42a8a2"/>
   </identifier>
   <identifier>
      <system value="https://gematik.de/fhir/erp/NamingSystem/GEM_ERP_NS_PrescriptionId"/>
      <value value="200.000.000.576.697.72"/>
   </identifier>
   <status value="billable"/>
   <code>
      <coding>
         <system value="http://terminology.hl7.org/CodeSystem/data-absent-reason"/>
         <code value="not-applicable"/>
      </coding>
   </code>
   <subject>
      <identifier>
         <system value="http://fhir.de/sid/pkv/kvid-10"/>
         <value value="X110465770"/>
      </identifier>
   </subject>
   <enterer>
      <identifier>
         <system value="https://gematik.de/fhir/sid/telematik-id"/>
         <value value="3-SMC-B-Testkarte-883110000116873"/>
      </identifier>
   </enterer>
   <enteredDate value="2023-06-04T23:05:42.273+00:00"/>
   <supportingInformation>
      <reference value="urn:uuid:c8b9cc08-0000-0000-0001-000000000000"/>
      <display value="https://fhir.kbv.de/StructureDefinition/KBV_PR_ERP_Bundle"/>
   </supportingInformation>
   <supportingInformation>
      <reference value="urn:uuid:c8b9cc08-0000-0000-0003-000000000000"/>
      <display value="https://gematik.de/fhir/erp/StructureDefinition/GEM_ERP_PR_Bundle"/>
   </supportingInformation>
   <supportingInformation>
      <reference value="#32e05db0-ba40-4967-9d7f-4b0bc19bd5e9"/>
      <display value="Binary"/>
   </supportingInformation>
</ChargeItem>`

Response 200

Hilft das?
