### ISSUE TITLE
Implement end-to-end encryption

### ISSUE THREAD

**Issue by riverside6** [gematik/api-erp#9]
As mentioned in gematik/api-erp#8, "patient data is the most intimate of our data". Therefore, E2EE should be mandatory. Especially for an app like this. So please implement E2EE.

Is the following news still up to date or obsolete?
[https://www.heise.de/news/E-Rezept-kommt-ohne-Ende-zu-Ende-Verschluesselung-4927214.html](https://www.heise.de/news/E-Rezept-kommt-ohne-Ende-zu-Ende-Verschluesselung-4927214.html)
The article is in german only. Sorry for this. Basically it says, all data beeing transfered between E-Rezept-App and Telematik-Infrastruktur (TI) are not encrypted.

**Comment by HendrikGematik** [comment]
The e-prescription project implements encryption at all stages of the process. 

- "in motion": all data is transported encrypted twice: VAU-encrypted and TLS encrypted
- "in use": all data is processed serverside within a security context of SGX enclaves
- "at rest": all data is encrypted on disk with keys that are not accessible by the operators
